name: Integration
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # echo:
  #   name: Echo
  #   runs-on: ubuntu-latest
  #   if: ${{ env.ACT }}
  #   steps:
  #     - run: |
  #         echo "============"
  #         echo "RUNNING VIA ACT"
  #         echo "============"
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_PORT: 5432
        DYNAMO_HOST: localhost
        DYNAMO_PORT: 8000

    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      dynamo:
        image: amazon/dynamodb-local
        ports:
          - 8000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm install
      # - run: npm run test -- --detectOpenHandles
      #   env:
      #     POSTGRES_HOST: localhost
      #     POSTGRES_PASSWORD: postgres
      #     POSTGRES_PORT: 5432
      #     DYNAMO_HOST: localhost
      #     DYNAMO_PORT: 8000
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
